version: "3"
services:
  db:
    container_name: ${DB_HOST}
  dspace:
    image: dspace:mirage2
    container_name: mirage2
    environment:
  #pgadmin4:
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: "user@dspace.com"
  #    PGADMIN_DEFAULT_PASSWORD: "dspace"
  #  ports:
  #    - "80:80"
